server:
  port: 9000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/workspace/project/db/db;MODE=Oracle
    username: sa
    password:
  h2:
    console:
      enabled: true
  view: 
    prefix: /WEB-INF/views/
    suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
